//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDate()
        {
            this.FactBills = new HashSet<FactBill>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime Date { get; set; }
        public byte Day { get; set; }
        public string DaySuffix { get; set; }
        public byte Weekday { get; set; }
        public string WeekDayName { get; set; }
        public string WeekDayName_Short { get; set; }
        public string WeekDayName_FirstLetter { get; set; }
        public byte DOWInMonth { get; set; }
        public short DayOfYear { get; set; }
        public byte WeekOfMonth { get; set; }
        public byte WeekOfYear { get; set; }
        public byte Month { get; set; }
        public string MonthName { get; set; }
        public string MonthName_Short { get; set; }
        public string MonthName_FirstLetter { get; set; }
        public byte Quarter { get; set; }
        public string QuarterName { get; set; }
        public int Year { get; set; }
        public string MMYYYY { get; set; }
        public string MonthYear { get; set; }
        public bool IsWeekend { get; set; }
        public bool IsHoliday { get; set; }
        public string HolidayName { get; set; }
        public string SpecialDays { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<int> FinancialQuater { get; set; }
        public Nullable<int> FinancialMonth { get; set; }
        public Nullable<System.DateTime> FirstDateofYear { get; set; }
        public Nullable<System.DateTime> LastDateofYear { get; set; }
        public Nullable<System.DateTime> FirstDateofQuater { get; set; }
        public Nullable<System.DateTime> LastDateofQuater { get; set; }
        public Nullable<System.DateTime> FirstDateofMonth { get; set; }
        public Nullable<System.DateTime> LastDateofMonth { get; set; }
        public Nullable<System.DateTime> FirstDateofWeek { get; set; }
        public Nullable<System.DateTime> LastDateofWeek { get; set; }
        public Nullable<short> CurrentYear { get; set; }
        public Nullable<short> CurrentQuater { get; set; }
        public Nullable<short> CurrentMonth { get; set; }
        public Nullable<short> CurrentWeek { get; set; }
        public Nullable<short> CurrentDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactBill> FactBills { get; set; }
    }
}
