//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDriver()
        {
            this.FactBills = new HashSet<FactBill>();
        }
    
        public int DriverKey { get; set; }
        public int DriverAltKey { get; set; }
        public string Name { get; set; }
        public string Provider { get; set; }
        public Nullable<int> Plate { get; set; }
        public string Model { get; set; }
        public string VehicleType { get; set; }
        public Nullable<double> PricePerKM { get; set; }
        public Nullable<int> VehicleCategory { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Status { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public Nullable<double> CurrentLat { get; set; }
        public Nullable<double> CurrentLng { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public string CurrentRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactBill> FactBills { get; set; }
    }
}
