//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDish()
        {
            this.FactBills = new HashSet<FactBill>();
        }
    
        public int DishKey { get; set; }
        public int DishAltKey { get; set; }
        public string DishName { get; set; }
        public Nullable<double> DishPrice { get; set; }
        public Nullable<short> DishDeleted { get; set; }
        public Nullable<short> DishActive { get; set; }
        public string DishEngName { get; set; }
        public string CurrentRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactBill> FactBills { get; set; }
    }
}
