//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimRestaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimRestaurant()
        {
            this.FactBills = new HashSet<FactBill>();
        }
    
        public int RestaurantKey { get; set; }
        public int RestaurantAltKey { get; set; }
        public string Name { get; set; }
        public Nullable<int> LaterOrder { get; set; }
        public string Position { get; set; }
        public string StartDelivery { get; set; }
        public string EndDelivery { get; set; }
        public Nullable<int> Active { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string ArabicAddress { get; set; }
        public string CityName { get; set; }
        public string CityArabicName { get; set; }
        public string CountryName { get; set; }
        public string AreaName { get; set; }
        public string AreaArabicName { get; set; }
        public string Street { get; set; }
        public string ArabicStreet { get; set; }
        public string Description { get; set; }
        public string ArabicDescraption { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<short> ShowPrices { get; set; }
        public Nullable<int> BeeorderRegisted { get; set; }
        public Nullable<int> TakeAway { get; set; }
        public Nullable<int> Delivery { get; set; }
        public Nullable<int> DineIn { get; set; }
        public string RestaurantType { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public Nullable<int> Copoun { get; set; }
        public Nullable<int> LateEstimation { get; set; }
        public Nullable<int> AutoClose { get; set; }
        public Nullable<int> MinimumOrder { get; set; }
        public Nullable<int> FreeDelivery { get; set; }
        public Nullable<int> DeliveryRegion { get; set; }
        public Nullable<double> DeliveryFee { get; set; }
        public Nullable<int> DeliveryProvider { get; set; }
        public Nullable<int> DeliveryAvialable { get; set; }
        public string CurrentRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactBill> FactBills { get; set; }
    }
}
