//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimUser()
        {
            this.FactBills = new HashSet<FactBill>();
        }
    
        public int UserKey { get; set; }
        public int UserAltKey { get; set; }
        public Nullable<int> Role { get; set; }
        public string Name { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string Near { get; set; }
        public string Floor { get; set; }
        public string AreaArabicName { get; set; }
        public string AreaEngName { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string CurrentRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactBill> FactBills { get; set; }
    }
}
