//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimVoucher
    {
        public int VoucherKey { get; set; }
        public int VoucherAltKey { get; set; }
        public int RestaurantId { get; set; }
        public string Voucher { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public string VoucherCategory { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> Taken { get; set; }
        public Nullable<System.DateTime> ValidateTime { get; set; }
    
        public virtual DimRestaurant DimRestaurant { get; set; }
    }
}
