//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacebookComment
    {
        public int Id { get; set; }
        public string PostId { get; set; }
        public string Name { get; set; }
        public string Mention { get; set; }
        public string Date { get; set; }
        public string Post { get; set; }
        public string Love { get; set; }
        public string Like { get; set; }
        public string Wow { get; set; }
        public string Angry { get; set; }
        public string Sad { get; set; }
        public string Haha { get; set; }
    
        public virtual FacebookPost FacebookPost { get; set; }
    }
}
