//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldDateDim
    {
        public int DateKey { get; set; }
        public System.DateTime FullDateLabel { get; set; }
        public Nullable<byte> DayNumberOfWeek { get; set; }
        public string DayNameOfWeek { get; set; }
        public Nullable<byte> DayNumberOfMonth { get; set; }
        public string DayNameOfMonth { get; set; }
        public string MonthName { get; set; }
        public Nullable<byte> MonthNumberOfYear { get; set; }
        public Nullable<short> CalenderYear { get; set; }
    }
}
